trigger:
- main

pr:
- '*'

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    displayName: 'Azure CLI Login'
    inputs:
      azureSubscription: 'p4sconnect2' # Use your service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # No need to run 'az login' here, the AzureCLI task handles authentication
    
  - script: |
      terraform init
      terraform plan -var-file=variables.tfvars
    displayName: 'Terraform Plan'
   
  - script: |
      terraform apply -auto-approve -var-file=variables.tfvars
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
