trigger:
- main

pr:
- '*'

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      
  - script: |
      terraform init
      terraform plan -var-file=variables.tfvars
    displayName: 'Terraform Plan'
   
  - script: |
      terraform apply -auto-approve -var-file=variables.tfvars
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
