trigger:
- main

pr:
- '*'

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)
    displayName: 'Azure CLI Login'
   
  - script: |
      terraform init
      terraform plan -var-file=variables.tfvars
    displayName: 'Terraform Plan'
   
  - script: |
      terraform apply -auto-approve -var-file=variables.tfvars
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
