trigger:
- main

pr:
- '*'

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      terraform init
      terraform plan -main.tf
    displayName: 'Terraform init'
  
  - script: |
      terraform apply -autoapprove
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
