trigger:
- main

pr:
- '*'

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      
  - script: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID;]$client_id"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;]$secret_id"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;]$subscription_id"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;]$tenant_id"
    displayName: 'Set Azure DevOps Variables'
    
  - script: |
      az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
    displayName: 'Azure CLI Login'
    
  - script: |
      terraform init
      terraform plan -var-file=variables.tfvars
    displayName: 'Terraform Plan'
   
  - script: |
      terraform apply -auto-approve -var-file=variables.tfvars
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      terraform apply -auto-approve -var-file=variables.tfvars
    displayName: 'Terraform Apply'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
