name: Deploy Index HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload index.html
        uses: azure/webapps-deploy@v2
        with:
          app-name: p4s1-appservice  # Replace with your web app name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Users\Consultant\armstorageacc\workflowsindex.html  # Path to your index.html file
