name: Terraform Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.4'

      - name: Configure Terraform workspace
        run: terraform init

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy using Terraform
        run: terraform apply -auto-approve

      - name: Upload index.html
        uses: azure/webapps-deploy@v2
        with:
          app-name: p4s1-appservice
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./Users\Consultant\armstorageacc\workflowsindex.html  # Path to your index.html file

      - name: Clean up
        run: terraform destroy -auto-approve
