trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
 azureSubscription: personal4slim


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'  # Adjust to your build output path
    archiveType: 'zip'
    archiveFile: $(Build.ArtifactStagingDirectory)/app.zip

- task: AzureWebApp@1
  inputs:
    appType: webApp
    azureSubscription: $(azureSubscription)  # Replace with your Azure service connection
    appName: 'p4sapp'  # Replace with your web app's name
    package: $(Build.ArtifactStagingDirectory)/app.zip
